# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import model_polisher
from model_polisher.parameters.base64_model_file import Base64ModelFile  # noqa: E501
from model_polisher.rest import ApiException


class TestBase64ModelFile(unittest.TestCase):
    """Base64ModelFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBase64ModelFile(self):
        """Test Base64ModelFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = model_polisher.models.base64_model_file.Base64ModelFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
