# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import model_polisher
from model_polisher.parameters.config import Config  # noqa: E501
from model_polisher.rest import ApiException


class TestConfig(unittest.TestCase):
    """Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfig(self):
        """Test Config"""
        # FIXME: construct object with mandatory attributes with example values
        # model = model_polisher.models.config.Config()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
