# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import model_polisher
from model_polisher.parameters.config_annotation_bigg_notes import ConfigAnnotationBiggNotes  # noqa: E501
from model_polisher.rest import ApiException


class TestConfigAnnotationBiggNotes(unittest.TestCase):
    """ConfigAnnotationBiggNotes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigAnnotationBiggNotes(self):
        """Test ConfigAnnotationBiggNotes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = model_polisher.models.config_annotation_bigg_notes.ConfigAnnotationBiggNotes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
