# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import model_polisher
from model_polisher.endpoints.full_run_api import FullRunApi  # noqa: E501
from model_polisher.rest import ApiException


class TestFullRunApi(unittest.TestCase):
    """FullRunApi unit test stubs"""

    def setUp(self):
        self.api = FullRunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_submit_file_post(self):
        """Test case for submit_file_post

        Upload a model file and parameters for the ModelPolisher.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
