# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import model_polisher
from model_polisher.parameters.post_validation import PostValidation  # noqa: E501
from model_polisher.rest import ApiException


class TestPostValidation(unittest.TestCase):
    """PostValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostValidation(self):
        """Test PostValidation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = model_polisher.models.post_validation.PostValidation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
