# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigAnnotation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bigg': 'ConfigAnnotationBigg',
        'annotate_db': 'ConfigAnnotationAnnotateDb'
    }

    attribute_map = {
        'bigg': 'bigg',
        'annotate_db': 'annotateDb'
    }

    def __init__(self, bigg=None, annotate_db=None):  # noqa: E501
        """ConfigAnnotation - a model defined in Swagger"""  # noqa: E501
        self._bigg = None
        self._annotate_db = None
        self.discriminator = None
        if bigg is not None:
            self.bigg = bigg
        if annotate_db is not None:
            self.annotate_db = annotate_db

    @property
    def bigg(self):
        """Gets the bigg of this ConfigAnnotation.  # noqa: E501


        :return: The bigg of this ConfigAnnotation.  # noqa: E501
        :rtype: ConfigAnnotationBigg
        """
        return self._bigg

    @bigg.setter
    def bigg(self, bigg):
        """Sets the bigg of this ConfigAnnotation.


        :param bigg: The bigg of this ConfigAnnotation.  # noqa: E501
        :type: ConfigAnnotationBigg
        """

        self._bigg = bigg

    @property
    def annotate_db(self):
        """Gets the annotate_db of this ConfigAnnotation.  # noqa: E501


        :return: The annotate_db of this ConfigAnnotation.  # noqa: E501
        :rtype: ConfigAnnotationAnnotateDb
        """
        return self._annotate_db

    @annotate_db.setter
    def annotate_db(self, annotate_db):
        """Sets the annotate_db of this ConfigAnnotation.


        :param annotate_db: The annotate_db of this ConfigAnnotation.  # noqa: E501
        :type: ConfigAnnotationAnnotateDb
        """

        self._annotate_db = annotate_db

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigAnnotation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigAnnotation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
