# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigPolishingReactionsFluxObjectives(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'objectives': 'object',
        'coefficients': 'object'
    }

    attribute_map = {
        'objectives': 'objectives',
        'coefficients': 'coefficients'
    }

    def __init__(self, objectives=None, coefficients=None):  # noqa: E501
        """ConfigPolishingReactionsFluxObjectives - a model defined in Swagger"""  # noqa: E501
        self._objectives = None
        self._coefficients = None
        self.discriminator = None
        if objectives is not None:
            self.objectives = objectives
        if coefficients is not None:
            self.coefficients = coefficients

    @property
    def objectives(self):
        """Gets the objectives of this ConfigPolishingReactionsFluxObjectives.  # noqa: E501


        :return: The objectives of this ConfigPolishingReactionsFluxObjectives.  # noqa: E501
        :rtype: object
        """
        return self._objectives

    @objectives.setter
    def objectives(self, objectives):
        """Sets the objectives of this ConfigPolishingReactionsFluxObjectives.


        :param objectives: The objectives of this ConfigPolishingReactionsFluxObjectives.  # noqa: E501
        :type: object
        """

        self._objectives = objectives

    @property
    def coefficients(self):
        """Gets the coefficients of this ConfigPolishingReactionsFluxObjectives.  # noqa: E501


        :return: The coefficients of this ConfigPolishingReactionsFluxObjectives.  # noqa: E501
        :rtype: object
        """
        return self._coefficients

    @coefficients.setter
    def coefficients(self, coefficients):
        """Sets the coefficients of this ConfigPolishingReactionsFluxObjectives.


        :param coefficients: The coefficients of this ConfigPolishingReactionsFluxObjectives.  # noqa: E501
        :type: object
        """

        self._coefficients = coefficients

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigPolishingReactionsFluxObjectives, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigPolishingReactionsFluxObjectives):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
