# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigAnnotationBiggNotes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'use_model_notes': 'object'
    }

    attribute_map = {
        'use_model_notes': 'useModelNotes'
    }

    def __init__(self, use_model_notes=None):  # noqa: E501
        """ConfigAnnotationBiggNotes - a model defined in Swagger"""  # noqa: E501
        self._use_model_notes = None
        self.discriminator = None
        if use_model_notes is not None:
            self.use_model_notes = use_model_notes

    @property
    def use_model_notes(self):
        """Gets the use_model_notes of this ConfigAnnotationBiggNotes.  # noqa: E501


        :return: The use_model_notes of this ConfigAnnotationBiggNotes.  # noqa: E501
        :rtype: object
        """
        return self._use_model_notes

    @use_model_notes.setter
    def use_model_notes(self, use_model_notes):
        """Sets the use_model_notes of this ConfigAnnotationBiggNotes.


        :param use_model_notes: The use_model_notes of this ConfigAnnotationBiggNotes.  # noqa: E501
        :type: object
        """

        self._use_model_notes = use_model_notes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigAnnotationBiggNotes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigAnnotationBiggNotes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
