# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigPolishingReactions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'check_mass_balance': 'object',
        'flux_objectives': 'ConfigPolishingReactionsFluxObjectives'
    }

    attribute_map = {
        'check_mass_balance': 'checkMassBalance',
        'flux_objectives': 'fluxObjectives'
    }

    def __init__(self, check_mass_balance=None, flux_objectives=None):  # noqa: E501
        """ConfigPolishingReactions - a model defined in Swagger"""  # noqa: E501
        self._check_mass_balance = None
        self._flux_objectives = None
        self.discriminator = None
        if check_mass_balance is not None:
            self.check_mass_balance = check_mass_balance
        if flux_objectives is not None:
            self.flux_objectives = flux_objectives

    @property
    def check_mass_balance(self):
        """Gets the check_mass_balance of this ConfigPolishingReactions.  # noqa: E501


        :return: The check_mass_balance of this ConfigPolishingReactions.  # noqa: E501
        :rtype: object
        """
        return self._check_mass_balance

    @check_mass_balance.setter
    def check_mass_balance(self, check_mass_balance):
        """Sets the check_mass_balance of this ConfigPolishingReactions.


        :param check_mass_balance: The check_mass_balance of this ConfigPolishingReactions.  # noqa: E501
        :type: object
        """

        self._check_mass_balance = check_mass_balance

    @property
    def flux_objectives(self):
        """Gets the flux_objectives of this ConfigPolishingReactions.  # noqa: E501


        :return: The flux_objectives of this ConfigPolishingReactions.  # noqa: E501
        :rtype: ConfigPolishingReactionsFluxObjectives
        """
        return self._flux_objectives

    @flux_objectives.setter
    def flux_objectives(self, flux_objectives):
        """Sets the flux_objectives of this ConfigPolishingReactions.


        :param flux_objectives: The flux_objectives of this ConfigPolishingReactions.  # noqa: E501
        :type: ConfigPolishingReactionsFluxObjectives
        """

        self._flux_objectives = flux_objectives

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigPolishingReactions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigPolishingReactions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
