# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigAnnotationAnnotateDb(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'annotate_with_adb': 'bool'
    }

    attribute_map = {
        'annotate_with_adb': 'annotateWithAdb'
    }

    def __init__(self, annotate_with_adb=False):  # noqa: E501
        """ConfigAnnotationAnnotateDb - a model defined in Swagger"""  # noqa: E501
        self._annotate_with_adb = None
        self.discriminator = None
        if annotate_with_adb is not None:
            self.annotate_with_adb = annotate_with_adb

    @property
    def annotate_with_adb(self):
        """Gets the annotate_with_adb of this ConfigAnnotationAnnotateDb.  # noqa: E501


        :return: The annotate_with_adb of this ConfigAnnotationAnnotateDb.  # noqa: E501
        :rtype: bool
        """
        return self._annotate_with_adb

    @annotate_with_adb.setter
    def annotate_with_adb(self, annotate_with_adb):
        """Sets the annotate_with_adb of this ConfigAnnotationAnnotateDb.


        :param annotate_with_adb: The annotate_with_adb of this ConfigAnnotationAnnotateDb.  # noqa: E501
        :type: bool
        """

        self._annotate_with_adb = annotate_with_adb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigAnnotationAnnotateDb, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigAnnotationAnnotateDb):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
