# coding: utf-8

"""
    Model Polisher API

    API for the Model Polisher.  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubmitFileBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config': 'Config',
        'model_file': 'str'
    }

    attribute_map = {
        'config': 'config',
        'model_file': 'modelFile'
    }

    def __init__(self, config=None, model_file=None):  # noqa: E501
        """SubmitFileBody - a model defined in Swagger"""  # noqa: E501
        self._config = None
        self._model_file = None
        self.discriminator = None
        self.config = config
        self.model_file = model_file

    @property
    def config(self):
        """Gets the config of this SubmitFileBody.  # noqa: E501


        :return: The config of this SubmitFileBody.  # noqa: E501
        :rtype: Config
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this SubmitFileBody.


        :param config: The config of this SubmitFileBody.  # noqa: E501
        :type: Config
        """
        if config is None:
            raise ValueError("Invalid value for `config`, must not be `None`")  # noqa: E501

        self._config = config

    @property
    def model_file(self):
        """Gets the model_file of this SubmitFileBody.  # noqa: E501


        :return: The model_file of this SubmitFileBody.  # noqa: E501
        :rtype: str
        """
        return self._model_file

    @model_file.setter
    def model_file(self, model_file):
        """Sets the model_file of this SubmitFileBody.


        :param model_file: The model_file of this SubmitFileBody.  # noqa: E501
        :type: str
        """
        if model_file is None:
            raise ValueError("Invalid value for `model_file`, must not be `None`")  # noqa: E501

        self._model_file = model_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubmitFileBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubmitFileBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
